openedx/frontend-platform

src/auth/index.js
src/auth/tests/AuthenticatedHttpClient.test.jsx
src/i18n/index.js
src/initialize.js

We weren’t passing the current URL through to ensureAuthenticatedUser during initialization, which meant that - if the user was logged out - we weren’t redirecting to the right page post-login.
Also removing FormattedHTMLMessage as an export - it was a mistake that it was available, as it’s not XSS safe.

fix: correctly passing URL through to auth during initialization

---

src/react/index.js

Two of the React components in @edx/frontend-platform are not exported and currently unusable by a consuming application (the import comes back as undefined).
This PR ensures `PageRoute` and `OptionalReduxProvider` are exported.

export PageRoute and OptionalReduxProvider

---

.env.development
.env.test
src/config.js
src/setupTest.js
src/utils.js

Also adding PUBLISHER_BASE_URL to config.  Wanting to add this config made me realize that it was going to cause applications to start throwing errors on startup, since none of them would have PUBLISHER_BASE_URL defined yet.  That seems like an unaccpetable, dangerous outcome of changing the config variables which one wouldn’t expect to be a breaking change.
Fixes #70 by avoiding the problem.

fix: ceasing to throw errors on undefined config

---

package-lock.json
package.json
src/auth/AxiosJwtAuthService.js
src/auth/MockAuthService.js
src/auth/index.js
src/auth/interface.js
src/config.js
src/utils.js

The mock auth service uses axios-mock-adapter in its implementation to allow mocking of any http client calls the auth service might make on behalf of an application.
This PR also fleshes out the docs for the auth service to try to add some detail around the differences between the interface, AxiosJwtAuthService, and new MockAuthService implementations.

feat: Adding a MockAuthService, improving docs

---

package-lock.json
package.json
src/auth/MockAuthService.js

MockAuthService misused axios-mock-adapter’s MockAdapter class.  It is not a drop-in replacement for an axios instance, but a companion object that, when configured, will intercept requests to the axios instance it was instantiated with.  You cannot call .get() or .post() on the mock itself - you need to call those on the original instance.  Therefore MockAuthService needs to return the real deal, and instantiators are responsible for using axios-mock-adapter if they want to.
This means the class’s primary use is to mock out the authenticated user loading.

fix: MockAuthService returns normal axios instances

---

src/auth/MockAuthService.js
src/auth/interface.js

There is a bug since, I believe, v1.4.0 where if the user's account should be hydrated (i.e., more user metadata fetched from an API), the app does not properly refresh once the hydration API request resolved.
This behavior can be seen in the `example` application within this repository.
This PR ensures the app is refreshed such that when the hydration API request resolves, the `authenticatedUser` has the additional user metadata as expected. It still does not block on rendering the app before the hydration API request resolves.
**Testing Instructions**
1. Checkout this branch locally: `astankiewicz/fix-user-hydration-reload`.
2. `npm install`, if necessary.
3. Start the example web app: `cd example && npm start`.
4. Observe the authenticated user's name appears after the hydration …

fix(auth): ensure app is refreshed after user hydration is complete

---

src/config.js
src/constants.js
src/index.js
src/initialize.js
src/initialize.test.js
src/react/AppProvider.jsx

For proper usage in the devstack are needed the changes from https://github.com/edx/frontend-build/pull/119 and from https://github.com/edx/frontend-build/pull/131
In this image I am serving the frontend-app-learning MFE in the devstack in the /learning/ path:

Set basename in order to allow the deployment of MFE in paths

---

src/initialize.js

attn @davidjoy 👍 
This is a workaround to enable this libaray's use on Gatsby-based sites which use `@edx/frontend-platform`.  
When building a production site, Gatsby makes a pass over all URLs for the site to do server side rendering, at which point it doesn't have access to `window` and other browser APIs, so calling `createBrowserHistory()` throws an exception.  This was happening when running `gatsby build` for deploys of our gatsby-based site for Gymnasium ([link](https://app.netlify.com/sites/gymnasium-gatsby/deploys/5f88ae1ae2169e0007996e02)).
When `window` doesnt' exist, the library falls back to creating a [`memoryHistory` object](https://github.com/ReactTraining/history/blob/master/docs/api-reference.md#creatememoryhistory), which is another implementation of the same interface …

Create SSR fallback for browser history in initialize.js

---

.env.development
.env.test

See https://github.com/edx/edx-platform/pull/24808 for full context.
I made this change before realizing that the `BASE_URL`s in this repo aren't actually used in MFE development at all, but I figure it'd be good to merge this for consistency anyway.

Prepend dev BASE_URL with http:// to fix login redirects

---

.env.development
.env.test
src/config.js
src/setupTest.js

Adds the following settings to the default configuration object:
* `LOGO_URL`
* `LOGO_TRADEMARK_URL`
* `LOGO_WHITE_URL`
* `FAVICON_URL`
This is needed for these configuration settings to be available through @edx/frontend-platform's `getConfig()`.

feat: add logo URLs to AppContext config

---

example/index.scss
package-lock.json
package.json
src/react/ErrorPage.jsx

Since we began using react-bootstrap passthru components in Paragon ~v10, the `ErrorPage` button text has been broken, containing no button text due to `Button` component props API changing.
This PR resolves that.

fix: resolve ErrorPage styles

---

package.json

We’re seeing issues in MFEs running paragon 13 where they can’t build in GoCD.
See version range rules here: https://docs.npmjs.com/cli/v6/using-npm/semver

fix: set the paragon peer dep to 12.8.0 to <14.0.0

---

src/analytics/SegmentAnalyticsService.js
src/analytics/interface.js
src/analytics/interface.test.js
src/initialize.js

If we are seeing an anonymous user, but the segment user id is still
set, we believe the segment user id is coming from a different user on
the same machine. This will make sure we clear out that storage and
then the indentify call will make a new anonymous id

fix: AA-513: Reset segment state if anon user and there is a segment user id

---

src/analytics/MockAnalyticsService.js
src/analytics/index.js
src/analytics/interface.js
src/analytics/interface.test.js
src/auth/MockAuthService.js
src/auth/index.js
src/index.js
src/logging/MockLoggingService.js
src/logging/index.js
src/testing/index.js
src/testing/initializeMockApp.js
src/testing/initializeMockApp.test.js
src/testing/mockMessages.js

The initializeMockApp function will setup mock versions of the analytics, auth, and logging services, see function description for more details.  The i18n service is set up as normal, since it makes no requests and is suitable for tests.
Using this should save a a bunch of manual test setup to mock logging/analytics calls and set up mock HTTP clients.
```
import { initializeMockApp } from '@edx/frontend-platform/testing';
import { logInfo } from '@edx/frontend-platform/logging';
describe('initializeMockApp', () => {
it('mocks things correctly', () => {
const { loggingService } = initializeMockApp();
logInfo('wut', {});
expect(loggingService.logInfo).toHaveBeenCalledWith('wut', {});
});
});
```

feat: Adds initializeMockApp for component testing

---

example/ExamplePage.jsx

`ensureConfig` and `mergeConfig` were called with incorrect params, this PR fixes the order and call them accordingly. 
Please refer to https://github.com/edx/frontend-platform/blob/master/src/config.js for correct function params

fix: correct examples according to defined params

---

.gitignore
src/react/PageRoute.jsx

Currently, we are dispatching twice as many page view events as we should be for any MFE that uses the `PageRoute` or `AuthenticatedPageRoute` components for routing. That is, for every real page view event, we are currently dispatching a second duplicate event. This adds lot of noise to our analytics and limits the validity of any page view based metrics.
The `useEffect` that controls dispatching a page event to Segment is executed whenever the the `match` object changes its reference without actually changing any of its values, e.g.:
```js
const match1 = { a: 2, b: 5 };
const match2 = { a: 2, b: 5 };
console.log(match1 == match2); // false
console.log(match1 === match2); // false
```
Due to this, we are sending erroneous page view events. Instead, stringifying the `match` object will …

fix: prevent duplicate page view events from being dispatched

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Updates the README to explicitly mention the example app included in this repo so that others may be more aware of it existing to QA against.

docs: include info about the example app and a PR template

---

src/config.js
src/logging/NewRelicLoggingService.js
src/logging/NewRelicLoggingService.test.js

The IGNORED_ERROR_REGEX variable is an optional parameter, so the config and
logging code should work fine without the variable being defined. As MFEs upgrade
to the newest version of frontend-platform, the new version should *not* require
the addition of IGNORED_ERROR_REGEX to function properly. This commit fixes the
previous code, which inadvertently required this variable to be defined.
TNL-7924

fix: Guard against a missing IGNORED_ERROR_REGEX environment variable.

---

src/logging/NewRelicLoggingService.js
src/logging/NewRelicLoggingService.test.js

At several places in certain MFEs, logInfo() is called with a caught error
object. But logInfo() has always assumed that only a string will be passed-in.
This situation causes a JSON object to be send to New Relic as the "message"
of an info log, which makes the info logs difficult to search.
This change adds support for either an info string -or- and error object being
sent to logInfo(). The proper "message" is logged either way.
Example:
In this MFE location, the error object is logged via logInfo():
https://github.com/edx/frontend-app-authn/blob/8fe7f93ac09b6dbee95069eca8d5284241234cae/src/register/data/sagas.js#L36
yielding a page action with an incorrect message:
```
{
"actionName": "INFO",
"appId": 799783938,
"appName": "prod-frontend-app-authn",
"asnLatitude": …
```

fix: Properly handle an error object sent into logInfo().

---

src/auth/AxiosJwtAuthService.js
src/auth/AxiosJwtAuthService.test.jsx
src/auth/AxiosJwtTokenService.js
src/auth/interface.js

Allow an optional parameter in `fetchAuthenticatedUser` that forces it to refresh the JWT token even if the token is not yet expired.
VAN-682

feat(auth): allow forceRefresh in fetchAuthenticatedUser

---

src/auth/AxiosJwtAuthService.test.jsx
src/auth/AxiosJwtTokenService.js

To help debug an odd issue where the cookie is not
appearing after a successful refresh, adding additional
data to test hypothesis that the browser time may have
drifted enough that the cookie is expired by the time it
arrives.

fix: add browser time to log message

---

src/analytics/SegmentAnalyticsService.js

This is an update to a previous fix: https://github.com/edx/frontend-platform/pull/208
If the Segment key is invalid or the user has blocked the segment domain using a plugin or extension; the promise does not get resolved and app initialization fails resulting into a blank page.
Set timeout to resolve the promise in case the Segment script is not loaded successfully.
VAN-689

fix: identifyAnonymousUser promise not resolving

---

docs/decisions/0005-token-null-after-successful-refresh.rst
src/auth/AxiosJwtTokenService.js

Access token null after successful refresh is an
unexpected error that we haven't been able to solve.
This introduces an ADR-like document to document the
findings thus far, and the de-facto decision to leave
the bug unresolved.
ARCHBOM-1150
**Author Concerns:**
This is not the typical ADR, but I'm not sure the best type of document for notes that are too long for a code comment. If you have a different suggestion, let me know.

docs: add access token null docs

---

src/analytics/SegmentAnalyticsService.js

If we timeout during segment identification, stop any further segment calls from happening, as they will fail anyway. And that just generates JS error churn.
This was noticed because about 18% of the learning MFE JS errors are now "Identify must be called before other tracking events." after we recently updated to the latest `frontend-platform`. I'm not sure this code path I fixed is 100% responsible for that uptick. But it certainly *can* result in that error.

fix(analytics): avoid errors when we bail on segment identification

---

README.md

Adds a clarification to the README around `getConfig` and `mergeConfig` in terms of how to access custom runtime configurations. This has continued to cause some confusion, especially since `console.log` will oddly return the custom property values as expected when expanding the object value (this is a [known issue](https://stackoverflow.com/questions/17546953/cant-access-object-property-even-though-it-shows-up-in-a-console-log) with `console.log`).

docs: clarify getConfig usage

---

src/analytics/SegmentAnalyticsService.js

The promise in `identifyAnonymousUser` has been causing issues with app initialization if a user blocks the analytics tools (e.g. segment.com, google-analytics.com) in their browser. Removing this promise, since we cannot handle the failures for google-analytics.com snippet which is loaded by the segment.min.js.
**Steps To Reproduce**
1. Visit https://authn.edx.org/register
2. Open browser inspector tools 
3. Go to the network tab and block www.google-analytics.com
4. Reload the page and you will see a blank page instead of registration form

fix: blank page issue if google analytics blocked

---

src/analytics/SegmentAnalyticsService.js

**Steps To Reproduce:**
1. Visit https://authn.edx.org/register
2. Open browser inspector tools
3. Go to the Network tab and block [www.googletagmanager.com](http://www.googletagmanager.com)
4. Reload the page and you will see a blank page instead of the register page

fix: blank page issue if GTM domain is blocked

---

package.json

Update paragon to <=^17.0.0 so we can test new npm version with paragon v16.y.z
When I build an MFE with npm 8 + node16, somehow the new npm resolution fails as following, due to paragon not being in the range
```
~/work/frontend-app-learner-portal-enterprise (master ✘)✖✹✭ ᐅ npm i                                     
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: frontend-app-learner-portal-enterprise@0.1.0
npm ERR! Found: @edx/paragon@16.14.7
npm ERR! node_modules/@edx/paragon
npm ERR!   @edx/paragon@"16.14.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @edx/paragon@">=10.0.0 <15.0.0" from @edx/frontend-platform@1.11.0
npm ERR! node_modules/@edx/frontend-platform
npm …
```

maint: update paragon range to resolve peer deps with new npm version

---

README.md

Intentionally labeling this a "fix" to generate a new release, now that the repo has been moved from the edx org to the openedx org.

fix: moving the README docs link to the new URL

---

.github/workflows/release.yml

Remove pin of semantic-release to v16 - this repo is now using node 16, so it can use later versions of semantic-release.

Update release.yml - unpin semantic-release

---

src/auth/AxiosJwtAuthService.js
src/auth/AxiosJwtAuthService.test.jsx
src/testing/initializeMockApp.test.js

Includes the user's "name" field in our authenticated user object.  
Example use case:
As a user, I'd like my name to appear in the pulldown in the header in edX rather than my username.
The idea is, After getting the name attribute in user object, we can override the desired behaviour in our fork of Header MFE e.g. [frontend-component-header-mitol](https://github.com/mitodl/frontend-component-header-mitol)
**Issue:**
fixes: https://github.com/mitodl/mitxpro/issues/2342

feat: Include user's name in authenticated user object

---

.github/workflows/lockfileversion-check.yml
package-lock.json

lockfileVersion for the package-lock.json generated by NPM6 was 1 but now as we've moved to Node16 and NPM8, package-lock.json should be generated using NPM8. lockfileVersion for package-lock.json generated using NPM8 is 2. So here we're going to check the lockfileVersion in package-lock.json

feat: Add package-lock file version check

---

docs/decisions/0006-middleware-support-for-http-clients.rst
docs/how_tos/automatic-case-conversion.rst
src/auth/AxiosJwtAuthService.js
src/auth/AxiosJwtAuthService.test.jsx
src/auth/MockAuthService.js
src/initialize.js
src/initialize.test.js

Resolves https://github.com/openedx/frontend-wg/issues/94.
Adds a way to add middleware when calling `getAuthenticatedHttpClient` or `getHttpClient`, and exports middleware for case conversions.
Still missing how-to doc.

feat: support conversation to/from snakecase for http clients

---

example/ExamplePage.jsx
example/index.jsx
package-lock.json
package.json
src/react/ErrorBoundary.test.jsx
src/react/ErrorPage.jsx

The `ErrorPage` relies on translated messages via react-intl's `FormattedMessage` component. However, it currently relies on consumers (i.e., MFEs) to wrap `ErrorPage` with an `IntlProvider` and pass a `locale` and `messages` prop. Instead, this PR proposes adding an `IntlProvider` to `ErrorPage`, pre-configuring its `locale` and `messages` props from the existing configuration in `@edx/frontend-platform` via its initialization.

fix: wrap ErrorPage with IntlProvider and pass messages

---

.eslintrc.js
package-lock.json
package.json
src/auth/MockAuthService.js
src/auth/interceptors/createRetryInterceptor.js
src/i18n/countries.js
src/i18n/languages.js
src/react/AppProvider.jsx
src/react/AuthenticatedPageRoute.test.jsx
src/react/OptionalReduxProvider.jsx
src/react/PageRoute.jsx
src/react/hooks.js

**Ticket:**
[42: Upgrade eslint to v8.x](https://github.com/openedx/frontend-wg/issues/42)
**Description**
- Updated `frontend-build `to v12 (Eslint was updated in `frontend-build` version resulting in it's version being bumped to v12. This PR updates `frontend-build` to reciprocate eslint version update)
- Resolved `eslint` issues post update

Updated front-build to v12

---

.env.development
.env.test
src/config.js
src/setupTest.js

This PR adds `config.SUPPORT_URL` for all frontends to use.
We needed this in `frontend-app-discussions` in config to add `Help` link in `LearningHeader`. 
Related PR: https://github.com/openedx/frontend-app-discussions/pull/251

feat: add SUPPORT_URL to config

---

src/i18n/countries.js
src/i18n/languages.js

- `import/extensions` rule was satisfied during frontend-build upgrade which resulted in resolution error for i18l lang modules for consumers, that change was reverted

fix: ignored import/extensions rule for lang extensions

---

docs/how_tos/caching.rst
package-lock.json
package.json
src/auth/AxiosJwtAuthService.test.jsx
src/auth/LocalForageCache.js

Swapping out `axios-cache-adapter` for `axios-cache-interceptor` since `axios-cache-adapter` is no longer maintained.
All of the previous caching behavior is supported, with additional ones supported by `axios-cache-interceptor`.
This is a **breaking change**.
Usages of `clearCacheEntry` will have to be updated.

feat: use axios cache interceptor for cache implementation

---

.github/workflows/ci.yml
docs/how_tos/caching.rst

BREAKING CHANGE: replacing axios-cache-adapter with axios-cache-interceptor

feat!: use axios cache interceptor for cache implementation

---

src/analytics/SegmentAnalyticsService.js
src/analytics/interface.test.js

Removed the identify call for anonymous users as it is causing anonymous id assigned by segment to change whenever a user lands on authn frontend.

feat: remove identify for anon users

---

.env.development
.env.test
src/config.js
src/setupTest.js

Added ACCOUNT_PROFILE_URL and ACCOUNT_SETTINGS_URL settings.
edx-platform PR: https://github.com/openedx/edx-platform/pull/30336
frontend-component-header PR: https://github.com/openedx/frontend-component-header/pull/210
https://github.com/openedx/public-engineering/issues/71
Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-17

FC-0001: Account pages -> micro-frontend

---

.github/workflows/release.yml

Used node 18 in `release` workflow which was breaking due to latest semantic release which has node 18 dependency.
Tested `npm ci`, `npm run build` and `npm run docs` locally 

fix: used node 18 to fix release workflow which has latest semantic release

---

jest.config.js
src/react/hooks.js
src/react/hooks.test.jsx

The previous release (3.4.0) added `useTrackColorSchemeChoice`, which relies on `window.matchMedia`. However, when running tests with this version of `@edx/frontend-platform` installed in MFEs, unless `window.matchMedia` is explicitly mocked in the consuming applications, any test that relies on `AppProvider` will fail.
This PR will gracefully handle when `window.matchMedia` is missing (e.g., `window.matchMedia?.('(prefers-color-scheme: dark)')`).

fix: handle missing window.matchMedia in useTrackColorSchemeChoice

---

src/i18n/lib.js
src/i18n/lib.test.js

this PR will add support for Persain Language (fa_IR) to the project. 
as I mentioned [here](https://github.com/openedx/frontend-platform/issues/384) right now we translated all edx-platform's components to Persian but when I wanted to add translations to the Microfronteds, RTL was not supported for fa-ir, so here we are :)

feat: Persian language support added

---

src/analytics/SegmentAnalyticsService.js
src/analytics/interface.test.js

This PR adds a check to avoid multiple identify calls to the segment.
**Context:**
In Authn, a user has an anonymous user ID in all segment events until the user is authenticated. A user is moved to the welcome page after registration and we want to fire a segment identify call on the welcome page because the user is now authenticated. But the identify call is not fired until the user reloads the page manually. So we are explicitly calling `identifyAuthenticatedUser` in the welcome page so that the user has its actual user ID in all the segment events.
This works fine and identify call is fired with the user ID on the welcome page.
**Issue:**
The issue is when a user reloads the page, there are 3 identify calls being fired.
1. The automatically identify call due to reloading.
2. Our …

fix: avoid multiple segment identify calls

---

package-lock.json
package.json

Fixes unit tests that were crashing due to issues in axios-mock-adapter

fix: fixed axios mock errros by upgrading axios-mock-adapter

---

src/analytics/SegmentAnalyticsService.js
src/analytics/interface.test.js

This pull request reverses the earlier change where the flag `hasIdentifyBeenCalled` was added to the `identifyAuthenticatedUser` and `identifyAnonymousUser` functions, along with their respective tests. This modification proved to be ineffective in addressing the problem we faced and did not serve the intended purpose.
The addition of a flag to the `identifyAuthenticatedUser` and `identifyAnonymousUser` functions caused a bug where the `identifyAnonymousUser` function was called with an anonymous ID on the registration page, setting the `hasIdentifyBeenCalled` flag to true. This caused the `identifyAuthenticatedUser` function was not called to perform the segment identify call after registration, as the `hasIdentifyBeenCalled` check was already true due to the previous function call. As …

revert: hasIdentifyBeenCalled check and its tests

---

src/analytics/SegmentAnalyticsService.js
src/analytics/interface.test.js

This pull request reverses the earlier change where the flag `hasIdentifyBeenCalled` was added to the `identifyAuthenticatedUser` and `identifyAnonymousUser` functions, along with their respective tests. This modification proved to be ineffective in addressing the problem we faced and did not serve the intended purpose.
The addition of a flag to the `identifyAuthenticatedUser` and `identifyAnonymousUser` functions caused a bug where the `identifyAnonymousUser` function was called with an anonymous ID on the registration page, setting the `hasIdentifyBeenCalled` flag to true. This caused the `identifyAuthenticatedUser` function was not called to perform the segment identify call after registration, as the `hasIdentifyBeenCalled` check was already true due to the previous function call. As …

fix: remove the hasIdentifyBeenCalled check and its corresponding tests

---

src/initialize.js
src/scripts/GoogleAnalyticsLoader.js
src/scripts/GoogleAnalyticsLoader.test.js
src/scripts/index.js

alternative implementation for https://github.com/openedx/frontend-platform/pull/471
Added support for GA4 to frontend-platform:
- implemented GoogleAnalyticsLoader class
- added loadExternalScripts function to  inititalize.js
- Added tests for GoogleAnalyticsLoader.
- The Google Analytics ID can be configured in the edx-platform MFE_CONFIG settings:
```
MFE_CONFIG = {
"GOOGLE_ANALYTICS_4_ID": "G-TEST"
}
```
or, the ID can be set in the frontend-platform .env file as:
`GOOGLE_ANALYTICS_4_ID="G-TEST"`

feat: Add GoogleAnalytics 4 to frontend-platform

---

src/auth/AxiosJwtAuthService.js
src/auth/AxiosJwtAuthService.test.jsx
src/logging/MockLoggingService.js
src/logging/NewRelicLoggingService.js
src/logging/NewRelicLoggingService.test.js
src/logging/interface.js

Adding setCustomAttribute to the logging service’s interface and implementing it in the NewRelicLoggingService.  Also using that in the auth service in order to set the userId as a custom attribute for all logged in users.
Also adding some more detail on code comments.

feat: set userId custom attribute for logging service

---

docs/decisions/0007-javascript-file-configuration.rst
env.config.js
example/ExamplePage.jsx
package.json
src/config.js
src/initialize.async.function.config.test.js
src/initialize.const.config.test.js
src/initialize.function.config.test.js
src/initialize.js
src/initialize.test.js

This adds the ability to configure an application via an env.config.js file rather than environment variables or .env files.  This mechanism is much more flexible and powerful than environment variables as described in the associated ADR.
It also improves documentation around how to configure applications, providing more detail on the various methods.
Finally, it allows the logging, analytics, and auth services to be configured via the configuration document now that we can supply an alternate implementation in an env.config.js file.  This allows configuration of these services without forking the MFE.
It doesn't remove the ability to supply a service implementation via the `initialize()` function's arguments since that would technically be a breaking change and it could conceivably be in …

feat: JavaScript file configuration of apps

---

package-lock.json
package.json
src/initialize.test.js

- Updated frontend-build 
- Fixed failing tests: In Jest v26, "implicit async" allowed test functions to both use the done callback and return a promise. This feature was deprecated in v27, the framework enforces the rule where test functions cannot use both done callback and return a value (promise or otherwise).

Updated frontend-build to bump jest version to v27

---

src/react/hooks/paragon/useParagonThemeCore.test.js
src/react/hooks/paragon/useParagonThemeVariants.test.js

This is a testing contribution to Theming Configuration in Runtime.
**Context**: https://github.com/openedx/frontend-platform/pull/440
C.C @adamstankiewicz

test: add testing to useParagonTheme hooks

---

package.json

The `frontend-platform@4.5.0` [PR](https://github.com/openedx/frontend-platform/pull/474) includes `frontend-build` as a peer dependency. Since `frontend-app-admin-portal` is installed with `frontend-build@12.9.0-alpha.1`, I have added `frontend-build 12.9.0-alpha.1` in the Peer Dependency to satisfy `frontend-app-admin-portal`.

Add frontend-build 12.9.0-alpha.1 in peer dep

---

package-lock.json
package.json

Paragon v21 was released as a breaking a11y change. This PR ensures the peer dependency allows consumers to install v21 without running into peer dependency errors.

feat: expand support for Paragon v21

---

src/initialize.js

This PR reorders the `initialize()` function of `frontend-platform` so that `internationalization` is initialized before `authentication`. Authentication error messages that need to be displayed to end users are internationalized and will fail if internationalization is not properly configured first.

fix: reordering initialization. i18n is required for auth errors

---

src/i18n/index.js
src/i18n/lib.js
src/i18n/lib.test.js

Fixed and exported the internal function `mergeMessages()` and refactored unit-tests to cover the new behavior. Previously this method would return an `object` identical to the one passed in (or an `object` version of an `array` passed in) and ignore/clobber any messages previously supplied. The new version fixes this function to actually merge new messages with existing ones. 
The method was never exported outside the package and the only internal use was in the `configure()` method which is refactored in this PR to use `lodash.merge()` directly. 
These changes support [OEP-65](https://github.com/openedx/open-edx-proposals/blob/426f6e09ffe615e77aa9205281d77012385a08d4/oeps/architectural-decisions/oep-XXXX-modular-micro-frontend-domains.rst#id1) and the related work in the repository …

fix: fixing and exporting mergeMessages()

---

package-lock.json
package.json

Updating dependencies to the latest react-redux@8.1.1
These changes support [OEP-65](https://github.com/openedx/open-edx-proposals/blob/426f6e09ffe615e77aa9205281d77012385a08d4/oeps/architectural-decisions/oep-XXXX-modular-micro-frontend-domains.rst#id1) and the related work in the repository frontend-app-shell which uses the [Piral framework](https://piral.io/) to federate MFEs. 
Piral is incopatible with the earlier version of react-redux@7.2.9 where the Redux store was not available during component rendering.

feat: updating dependency to react-redux@8.1.1

---

package-lock.json
package.json

Updating dependencies to the latest `paragon@21.1.2` and to `react-intl@6.4.0`
These changes support [OEP-65](https://github.com/openedx/open-edx-proposals/blob/426f6e09ffe615e77aa9205281d77012385a08d4/oeps/architectural-decisions/oep-XXXX-modular-micro-frontend-domains.rst#id1) and the related work in the repository `frontend-app-shell` which uses the [Piral framework](https://piral.io) to federate MFEs. 
Piral is incopatible with the earlier version of `react-intl@5.25.1` and generated errors because internationalization components were not properly rendered in the React component hierarchy.

feat: Updating dependency to Paragon@21.1.2 and React-intl@6.4.0

---

.github/workflows/manual-publish.yml

Adds the `manual-publish.yml` GitHub Action workflow to be able to backport changes to previous versions of frontend-platform.
See this document for more details: https://openedx.atlassian.net/wiki/spaces/FEDX/pages/3755868171/How+to+backport+a+change+to+a+previous+version+with+semantic-release+for+JS+libraries

chore: add manual-publish.yml Github Action workflow

---

.github/workflows/manual-publish.yml
Makefile

Running the `manual-publish.yml` workflow file failed due to missing `validate-no-uncommitted-package-lock-changes` Make target: https://github.com/openedx/frontend-platform/actions/runs/6101546207/job/16558102918
Removes `validate-no-uncommitted-package-lock-changes` from manual-publish.yml as the Makefile in this repo does not specify that Makefile target. The `manual-publish.yml` file was largely copy/pasted from frontend-component-footer-edx which _does_ have that Makefile target.
Opting to remove the workflow step to `validate-no-uncommitted-package-lock-changes` rather than adding the Makefile target given we don't get this in any of the other workflow files for this repo today.

chore: remove `validate-no-uncommitted-package-lock-changes` from manual-publish.yml

---

.github/workflows/manual-publish.yml

Also carried over from copy/paste of another repo's `manual-publish.yml` file. frontend-platform has no need for the `i18n_extract` step, so this PR removes it from the workflow.

chore: remove i18n_extract from manual-publish.yml

---

package-lock.json
package.json

`react-redux` peerDependency was updated in [#549 ](https://github.com/openedx/frontend-platform/pull/549)causing CI failure for its consumers. Since the public API (`<Provider>`, `connect`, `useSelector`/`useDispatch`) remains unchanged and for most use-cases applications using v7 would work with v8 (apart from some rare API like `connectAdvanced` which have been removed), peerDependency for `react-redux` was updated in order to prevent any dependency issues for consumers.

fix: updated react-redux peerDependency to resolve CI failure

---

package-lock.json
package.json

Reverts #548 and #547 since its breaking consumers and we have to release it as Breaking Change
- [] Consider testing your code modifications in another local micro-frontend using local aliases configured via [the `module.config.js` file in `frontend-build`](https://github.com/openedx/frontend-build#local-module-configuration-for-webpack).

fix: revert react-redux, react-intl and paragon to release it as breaking change

---

src/react/ErrorBoundary.jsx
src/react/ErrorBoundary.test.jsx

The `ErrorBoundary` component becomes more flexible with the ability to pass the component you want to render in place of just the `ErrorPage` component. This feature is similar to the [react-error-boundary](https://github.com/bvaughn/react-error-boundary.git) library.

feat: fallback component as prop for ErrorBoundary

---

src/initialize.js
src/react/AppProvider.jsx

As part of the React Router v5 -> v6 upgrade, history was no longer being passed in. This broke the Tutor deployment method of MFEs, which puts all the MFEs in a common server and uses different top-level dirs to separate them.
The fix for this is to pass in an explicit basename to the Router.

fix: make Tutor-MFE config compatible with React Router v6

---

src/utils.js
src/utils.test.js

This PR fixes the following `href` property issue in gatsby build:

fix: href property issue in gatsby build

---

package-lock.json
package.json

- Bumped `@formatjs/intl-pluralrules` & `@formatjs/intl-relativetimeformat` major version 

fix: bumped formatjs packages

---

package-lock.json
package.json

Demoted `react-intl` to v5 in light of breaking tests for consumers.

fix: demoted react-intl to v5 

---

src/testing/mockMessages.js

Locale missing console warnings for `fa`, `fa-ir` are raised while running test cases. Same locales warnings are raised in many MFEs. Such as Discussions, Course-authoring.
- [ ✅] Consider running your code modifications in the included example app within `frontend-platform`. This can be done by running `npm start` and opening http://localhost:8080.
- [ ✅] Consider testing your code modifications in another local micro-frontend using local aliases configured via [the `module.config.js` file in `frontend-build`](https://github.com/openedx/frontend-build#local-module-configuration-for-webpack).
- [✅ ] Verify your commit title/body conforms to the conventional commits format (e.g., `fix`, `feat`) and is appropriate for your code change. Consider whether …

fix: add fa, fa-ir locales in mockMessages

---

src/react/hooks/paragon/useParagonThemeCore.js
src/react/hooks/paragon/useParagonThemeVariants.js

fix: update links in head and *isLoaded to true

---

src/react/hooks/paragon/useParagonTheme.test.js
src/react/hooks/paragon/useParagonThemeCore.test.js
src/react/hooks/paragon/utils.test.js

This is a testing contribution to Theming Configuration in Runtime, covering useParagonTheme hook, and the utils file.
Context: https://github.com/openedx/frontend-platform/pull/440
C.C @adamstankiewicz

test: add test to useParagonTheme hook and paragon utils

---

.eslintrc.js
babel.config.js
example/index.scss
jest.config.js
package-lock.json
package.json
src/react/ErrorPage.jsx
webpack.dev.config.js

Part of https://github.com/openedx/axim-engineering/issues/23#issuecomment-1889749893
BREAKING CHANGE: consuming applications must now install `paragon` from the `@openedx` scope, `paragon` installed from the `@edx` scope will no longer satisfy the peer dependency
BREAKING CHANGE: consuming applications must now install `frontend-build` from the `@openedx` scope, `frontend-build` installed from the `@edx` scope will no longer satisfy the peer dependency

chore!: update dependencies to use `@openedx` scope

---

.github/workflows/release.yml

semantic-release [version 23](https://github.com/semantic-release/semantic-release/releases/tag/v23.0.0) includes the following breaking change:
* support for node v18 has been dropped and the minimum for v20 is now v20.8.1
This pins the release workflow to version 22 until we move away from node 18.

fix(ci): specify semantic release version that is compatible with node 18

---

package-lock.json
package.json

Paragon v22 was released. The current peer dependencies in package.json won't allow consumers to upgrade to Paragon v22 until explicit support for the new version is added to package.json.

chore: bump and support paragon v22

---

.gitignore
Makefile
package.json

Allow MFEs and others to use this repo translations via [openedx-translations](https://github.com/openedx/openedx-translations) GitHub repository.
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).

feat: extract translations for atlas pull | FC-0012

---

.github/workflows/release.yml
.releaserc

Start publishing `alpha` packages, in order to facilitate testing of breaking changes.
This was motivated by https://github.com/openedx/frontend-build/pull/415.

build: start releasing alpha packages

---

.github/workflows/ci.yml
.github/workflows/manual-publish.yml

Per https://openedx.atlassian.net/wiki/spaces/COMM/pages/3438280709/Adding+Codecov, I think this is the right thing to do.
@dcoa , could you review this?

build: upgrade codecov from v3 to v4, use secret

---

src/i18n/countries.js
src/i18n/languages.js

This changes a few stray usages of Node's `require()` syntax to the modern ES6 module `import` syntax. It should have basically no effect, except that it makes the code more compatible with a wider range of tools. For example, building an MFE with Vite instead of Webpack requires this change.

core: convert i18n data imports to import syntax

---

package-lock.json
package.json
webpack.dev.config.js

Without defining the `app` entrypoint explicitly, `HtmlWebpackPlugin` does not have assets available for `app` when its referenced in the `chunks` option.
The `webpack.common.config.js` in frontend-build defines an `app` entrypoint, but the frontend-platform example app overrides it.

chore: define app entry point for webpack.dev.config.js

---

example/index.jsx
package-lock.json
package.json
src/setupTest.js

`core-js` and `regenerator-runtime` are marked as a development dependencies (for the test suites), but the tests actually pass fine without them. I think they should just be removed.
Context: they are compatibility layers for older browsers/runtimes, and aren't needed in 2024.

chore: remove core-js and regenerator-runtime

---

example/AuthenticatedPage.jsx
example/ExamplePage.jsx
example/index.jsx
example/messages.js
jest.config.js
package-lock.json
package.json
src/react/AppProvider.jsx
src/react/AppProvider.test.jsx
src/react/AuthenticatedPageRoute.jsx
src/react/OptionalReduxProvider.jsx
src/react/OptionalReduxProvider.test.jsx
src/react/hooks.test.jsx

Related PRs:
* https://github.com/openedx/frontend-build/pull/625
The Open edX MFEs are overdue to support React 18 (especially as React 19 is already out now, too). Some efforts have been started to support React 18 in the shared JavaScript libraries, such as Paragon (https://github.com/openedx/paragon/pull/3367, v22 and v23).
By enabling support for React 18 (should be additive-only), we can further enable incremental migration to React 18 within MFEs. Most of the changes are within the example MFE included in this repository for testing.
The [React 18 Upgrade Guide](https://react.dev/blog/2022/03/08/react-18-upgrade-guide) was followed.

Enable support for React 18

---

src/react/hooks/paragon/useParagonThemeCore.test.js
src/react/hooks/paragon/useParagonThemeUrls.test.js
src/react/hooks/paragon/useParagonThemeVariants.test.js
src/react/hooks/paragon/utils.js
src/react/hooks/paragon/utils.test.js

This PR manages the cases where the protocol is not present in the `BASE_URL` environment variable when is used for creating urls in the themes hook. 

fix: manage if the BASE_URL does not have the protocol for themes urls

---

src/react/hooks/paragon/useParagonThemeUrls.js
src/react/hooks/paragon/useParagonThemeUrls.test.js

If the brand package is installed with a compatible version of design tokens and define `PARAGON_THEMES_URLS={}` to use the local files, this one is not creating the corresponding urls - only the Paragon default ones. This PR aims to add the logic to permit the creation of those urls. 
I added some improvements in the test file based on the comments of the original PR https://github.com/openedx/frontend-platform/pull/689#discussion_r1977840132

fix: create the brand fallback for {} PARAGON_THEME_URLS

---

src/react/hooks/paragon/useParagonThemeUrls.js
src/react/hooks/paragon/useParagonThemeUrls.test.js

This PR aims to allow the creation of URLs with only `brandOverride` definition.
Solving the following use case https://github.com/openedx/frontend-platform/issues/808

fix: support not setting default in variant when using PARAGON_THEME_URLS

---

package-lock.json
package.json

**Related discussions:**
* https://github.com/openedx/frontend-platform/pull/787
* https://github.com/openedx/open-edx-proposals/pull/615
**Corresponding PR:**
* https://github.com/openedx/frontend-app-communications/pull/221
Demonstrates treating `@openedx/frontend-build` as an **optional** peer dependency within `@edx/frontend-platform`, such that consuming MFEs no longer considers `@openedx/frontend-build` as a direct dependency, via:
```json
{
"peerDependenciesMeta": {
"@openedx/frontend-build": {
"optional": true
}
}
}
```
From @brian-smith-tcril [here](https://github.com/openedx/frontend-platform/pull/787#issuecomment-2775706607):
> As for `frontend-build` specifically, the fact that it is currently in `frontend-platform`'s `peerDependencies` means that MFEs adding …

fix: treat @openedx/frontend-build as an optional peerDep to avoid direct dep in consuming MFEs

---

README.md
docs/decisions/0007-javascript-file-configuration.rst
src/config.js
src/initialize.js
src/react/hooks/paragon/useParagonTheme.js

This PR provides some minor updates to some of the documentation of this package. These were improvements I noticed could be made while working on #809.

docs: update outdated info, reword, reformat

---

src/config.js

Fix rendering issues of [reference-style](https://www.markdownguide.org/basic-syntax/#reference-style-links) markdown link to ADR in the Config module docs.
Resolves #817 .
I tested this change locally by running `npm run docs` and then opening `docs/api/@edx/frontend-platform/1.0.0-semantically-released/index.html` in Chrome. The Config link on the index page was fixed and the link on the Config page (`module-Config.html`) rendered correctly.

docs: move reference-style link above module tag

---

src/i18n/countries.js
src/i18n/lib.js
src/i18n/lib.test.js

In our edx-plasform app, we need VIetnamese support language (in MFE). So this PR will add vi locate into i18n

feat: add Vietnamese language support
