src/base/AppProvider.test.jsx
src/base/handlers/i18n.js
src/i18n/README.rst
src/i18n/injectIntlWithShim.jsx
src/i18n/lib.js
src/i18n/lib.test.js

Remove the `../logging` reference in `injectIntlWithShim`

fix: configure i18n with logging service

---

src/auth/index.js
src/auth/tests/AuthenticatedHttpClient.test.jsx

Rename the existing getAuthenticatedUser to fetchAuthenticatedUser.
Doesn't use it in base or anywhere yet.

refactor: move getAuthenticatedUser and hydrateAuthenticatedUser into auth

---

example/AuthenticatedPage.jsx
example/ExamplePage.jsx
example/index.jsx
src/analytics/SegmentAnalyticsService.js
src/auth/index.js
src/config/index.js
src/config/interface.js
src/i18n/lib.js
src/init/index.js
src/init/interface.js
src/logging/index.js
src/pubSub/PubSubJsService.js
src/pubSub/index.js
src/pubSub/interface.js
src/react/AppProvider.jsx
src/react/AuthenticatedPageRoute.test.jsx
src/react/index.js

Hooks up some moved things. configService and pubSubService are no longer initialized in `init/initialize` because they are used prior in the MFE App.

fix  example app

---

src/auth/tests/AuthenticatedHttpClient.test.jsx
src/auth/utils.js

Add request, response, or config to message

fix: make axios error messages clearer

---

src/auth/index.js
src/react/AuthenticatedPageRoute.jsx
src/react/AuthenticatedPageRoute.test.jsx
src/react/PageRoute.jsx

- Added redirectUrl prop to AuthenticatedPageRoute to enable redirection to pages other than login.
- Refactored PageRoute to allow all react-router-dom Route props
- Added getLoginRedirectUrl and getLogoutRedirectUrl for direct access to login/logout URL creation.
This fixes #63

feat: More flexible page routes

---

example/index.jsx
package-lock.json
package.json
public/index.html
src/analytics/SegmentAnalyticsService.js
src/auth/AxiosJwtAuthService.js
src/auth/AxiosJwtAuthService.test.jsx
src/auth/MockAuthService.js
src/auth/interface.js
src/config.js
src/constants.js
src/i18n/injectIntlWithShim.jsx
src/i18n/lib.test.js
src/initialize.js
src/initialize.test.js
src/logging/NewRelicLoggingService.js
src/logging/index.js
src/pubSub.js
src/react/AppProvider.jsx
src/react/AuthenticatedPageRoute.test.jsx
src/react/ErrorBoundary.jsx
src/react/ErrorPage.jsx
src/react/OptionalReduxProvider.jsx
src/utils.js
src/utils.test.js

Also opportunistically removing a strange script tag loading ‘index.js’ in the example app, which doesn’t work.

fix: bumping version of frontend-build to latest

---

src/auth/interface.js
src/logging/interface.js

Updates docs to better reflect what's in the code. 😄

Docs updates

---

src/analytics/SegmentAnalyticsService.js
src/analytics/interface.js
src/analytics/interface.test.js

Please see commit messages for details.  This PR is best reviewed commit-by-commit.

fix: Conditionally initialize Segment only if a SEGMENT_KEY is present.

---

package.json

The change is required for frontend-app-learning to be to use the new version of frontend-platform.

Loosen paragon dependency version bound.

---

.env.development
.env.test
src/config.js
src/logging/NewRelicLoggingService.js
src/logging/NewRelicLoggingService.test.js

This PR was created mainly to force a patch version bump and a new release of frontend-platform, after the previous `chore:` commit which was really more of a feature. But it also sharpens the docstring.

fix: Corrects some of the docstring text from IGNORED_ERROR_REGEX.

---

src/logging/interface.js

These documentation changes were missed in the previous logging changes.

docs: Add recent changes to the logging interface documentation.

---

README.md

Add a link to the GitHub Pages site to the README.

docs: add full doc link to README.md

---

docs/how_tos/i18n.rst

Update the docs to reflect preferable way to define messages in a MFE.

docs: updating i18n docs

---

package.json

Also clean up ^ on other packages.

fix: allow paragon 16

---

src/analytics/SegmentAnalyticsService.js

If the Segment key is invalid or the user has blocked the analytics tools using a plugin or extension; the promise does not get resolved and app initialization fails resulting into a blank page.

fix: identifyAnonymousUser promise

---

src/analytics/SegmentAnalyticsService.js

Also refactored the logic of resolving the promise for `identifyAnonymousUser`.
Removed the setTimeout logic and used a custom event to resolve the promise if the script has failed to load.

fix(analytics): events not firing for anonymous users

---

.travis.yml

rotate: travis github token (PSRE-1053)

---

docs/how_tos/i18n.rst

chore: update Transifex document

---

.github/workflows/ci.yml
package-lock.json
package.json

JIRA: https://openedx.atlassian.net/browse/BOM-3336

fix: Use strategy matrix in CI workflow

---

src/i18n/index.js

Exports useIntl and createIntl from react-intl library.

feat: export useIntl and createIntl from react-intl

---

src/i18n/index.js

Adds docstrings for useIntl and createIntl exports.

chore: add docstrings for useIntl and createIntl

---

.github/workflows/release.yml

build: pin npm to 8.5.x in release.yml

---

.github/workflows/npm-unpublish.yml

build: add unpublish workflow

---

.github/workflows/ci.yml

build: add release preview to ci workflow

---

package-lock.json

- Bumped recursive-readdir & loader-utils

refactor: bumped recursive-readdir & loader-utils

---

src/i18n/lib.test.js

This PR fixes the failing test related to translations.

fix: failing test related to translations

---

catalog-info.yaml

Added catalog-info.yaml file to complete maintianership process

feat: added catalog-info.yaml file

---

README.md

Hi there.
there were a couple of issues on the readme file. 1 typo and a couple of tone improvements. which was fixed in this PR

README Typos and tone issues

---

src/auth/AxiosJwtAuthService.test.jsx

Tests cases are failing inconsistently with either empty response `AxiosError` or the jest test times out. The issue was traced to be with httpbin.org for which even direct hits at time would result in 504. To pass all the test cases consistently, `AxiosJwtAuthService` test suit has been updated to use [jsonplaceholder](https://jsonplaceholder.typicode.com/) instead of [httpbin.org](http://httpbin.org/).

test: Httpbin calls replaced with jsonplaceholder to prevent test cases from timing out

---

src/auth/AxiosJwtAuthService.test.jsx
src/auth/utils.js

It is difficult to group the current axios error messages, because they contain a bunch of data that can vary based on i18n or course ids in urls, etc. Since this data is provided in the custom attributes separately, it is being removed from the actual  messages.
**Note**: This is a starter PR, but probably requires test updates.

feat: update axios log messages

---

docs/how_tos/i18n.rst

Update transifex setup instruction

chore: update transifex setup instruction

---

.github/workflows/manual-publish.yml

Adds `./dist` to `npm publish --tag  ${{github.event.inputs.tag}}` such that only the contents of the `dist` folder are published for backported versions.
Verified locally with `--dry-run`: 
```
❯ npm publish ./dist --dry-run
npm notice 
npm notice 📦  @edx/frontend-platform@4.6.2
npm notice === Tarball Contents === 
npm notice 34.5kB LICENSE                                                           
npm notice 9.5kB  README.md                                                         
npm notice 375B   analytics/index.js                                                
npm notice 917B   analytics/index.js.map                                            
npm notice 3.5kB  analytics/interface.js                                            
npm notice 6.3kB  analytics/interface.js.map …
```

chore: add dist directory to npm publish in manual-publish.yml

---

package-lock.json
package.json

Upgraded frontend-build to resolve security issues

fix: upgraded frontend-build to fix security issues

---

src/utils.js

This PR fixes the `document is not defined` issue of `gatsby build`. 
[[Ref](https://github.com/openedx/frontend-app-learner-portal-programs/actions/runs/6504551774/job/17666848008?pr=289)]

fix: document being undefined issue

---

package-lock.json
package.json

Updating dependencies `paragon@21.1.2`,` react-intl@6.4.0` & `react-redux@8.1.1`

feat: updated paragon@21.1.2, react-intl@6.4.0 & react-redux@8.1.1

---

package-lock.json
package.json

Reverts openedx/frontend-platform#583 in favour of a major breaking change release, since it is causing issues with consumers

Revert "feat: updated paragon@21.1.2, react-intl@6.4.0 & react-redux@8.1.1"

---

package-lock.json
package.json

Bumped minor `paragon` version & major `react-intl` version to v6

feat: bumped react-intl & paragon versions

---

docs/how_tos/i18n.rst

docs: update i18n file

---

catalog-info.yaml

Continuing maintainership updates for 2U 2024.

chore: update catalog-info owner

---

catalog-info.yaml

Adolfo, Brian and Braden have been defacto maintainers here just make
that official.

docs: Update the maintainer.
